name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Lint Frontend
        working-directory: ./frontend
        run: npm run lint
      # - name: Test Frontend
      #   working-directory: ./frontend
      #   run: npm test # Assuming you have tests configured
      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

  embedding_service:
    runs-on: ubuntu-latest
    # needs: frontend # Can run in parallel if no direct dependency for build/lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Embedding Service Dependencies
        working-directory: ./services/embedding_service
        run: |
          pip install flake8 pytest # Install linting/testing tools
          pip install -r requirements.txt
      - name: Lint Embedding Service
        working-directory: ./services/embedding_service
        run: flake8 .
      # - name: Run Embedding Service Tests
      #   working-directory: ./services/embedding_service
      #   run: pytest # Assuming you have tests configured

  scripts:
    runs-on: ubuntu-latest
    # needs: embedding_service # Can run in parallel
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python for Scripts
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Script Dependencies
        working-directory: ./scripts
        run: |
          pip install flake8 # Install linting tools
          pip install -r requirements.txt
      - name: Lint Scripts
        working-directory: ./scripts
        run: flake8 . 